version: '3.6'

services:

  #---------------------------------------------------------------
  discovery:
    image: "consul:1.6"
    hostname: discovery
    command: "agent -config-file /consul/config/config.json"
    ports:
      - "8500:8500"
    volumes:
      - ./discovery/config:/consul/config
    networks:
      - sample-app


  #---------------------------------------------------------------
  config:
    hostname: config
    build:
      context: .
      dockerfile: config/docker/Dockerfile
    environment:
      - CONFIG_PROFILES=default
      - GIT_USER=jorge3186
      - GIT_PASSWORD
      - CONFIG_PORT=8888
    networks:
      - sample-app


  #---------------------------------------------------------------
  exchangerates:
    build:
      context: .
      dockerfile: exchange-rates/docker/Dockerfile
    links:
      - discovery
      - config
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - CONFIG_HOST=config
      - CONFIG_PORT=8888
      - EX_RATES_PORT=0
    depends_on:
      - discovery
      - config
    networks:
      - sample-app


  #---------------------------------------------------------------
  currencyconverter:
    build:
      context: .
      dockerfile: currency-converter/docker/Dockerfile
    links:
      - discovery
      - config
      - exchangerates
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - CONFIG_HOST=config
      - CONFIG_PORT=8888
      - CURR_CONV_PORT=0
    depends_on:
      - discovery
      - config
    networks:
      - sample-app


  #---------------------------------------------------------------
  ui:
    build:
      context: .
      dockerfile: ui/docker/Dockerfile
    depends_on:
      - discovery
      - currencyconverter
      - exchangerates
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
    networks:
      - sample-app


  #---------------------------------------------------------------
  gateway:
    hostname: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      - DISCOVERY_HOST=discovery
      - DISCOVERY_PORT=8500
    ports:
      - "8090:80"
    depends_on:
      - discovery
    networks:
      - sample-app



networks:
  sample-app:
    driver: "bridge"