version: '3.6'

services:

  #---------------------------------------------------------------
  discovery:
    image: "consul:1.6"
    hostname: discovery
    environment:
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true, \"leave_on_terminate\": true, \"ui\": true, \"dns_config\": {\"allow_stale\": false}}"
    command: "agent -server -client=0.0.0.0 -bootstrap"
    ports:
      - "8500:8500"
    networks:
      - sample-app


  #---------------------------------------------------------------
  config:
    hostname: config
    build:
      context: .
      dockerfile: config/docker/Dockerfile
    environment:
      - CONFIG_PROFILES=default
      - GIT_USER=jorge3186
      - GIT_PASSWORD
      - CONFIG_PORT=8888
    networks:
      - sample-app


  #---------------------------------------------------------------
  exchangerates:
    build:
      context: .
      dockerfile: exchange-rates/docker/Dockerfile
    links:
      - discovery
      - config
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - CONFIG_HOST=config
      - CONFIG_PORT=8888
      - EX_RATES_PORT=0
    depends_on:
      - discovery
      - config
    networks:
      - sample-app


  #---------------------------------------------------------------
  gateway:
    hostname: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      - DISCOVERY_HOST=discovery
      - DISCOVERY_PORT=8500
    ports:
      - "8090:80"
    depends_on:
      - discovery
    networks:
      - sample-app



networks:
  sample-app:
    driver: "bridge"