# -- DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-cloud-app-ui-deployment
  labels:
    group: sample-cloud-app
    app: sample-ui
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
       app: sample-ui
  replicas: 1
  template:
    metadata:
      labels:
        group: sample-cloud-app
        app: sample-ui
    spec:
      restartPolicy: Always
      containers:
        - name: ui
          image: sample-ui:latest
          imagePullPolicy: Never
          args:
            - '8080'
          env:
            - name: CONSUL_HOST
              value: discovery
            - name: CONSUL_PORT
              value: '8500'
          ports:
            - containerPort: 8080

---
# -- HORIZONTAL AUTO SCALE
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-cloud-app-ui-autoscaler
  labels:
    group: sample-cloud-app
    app: sample-ui
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    name: sample-cloud-app-ui-deployment
    kind: Deployment
    apiVersion: apps/v1
  targetCPUUtilizationPercentage: 75